abstract: POE chat component for twitter.com
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-Client-Twitter
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTTP::Date: 0
  HTTP::Request: 0
  JSON::Any: 0
  POE: 0
  POE::Component::Client::HTTP: 0
  URI: 0
version: 0.01
